#!/bin/bash

if [ -z $1 ]; then
    echo -e "\033[1mUsage: ./part disk_name [image.sb] [fs_type]\033[0m"
    exit
fi

if [ ! -b "$1" ]; then
    echo -e "\033[1mError: $1 disk not found\033[0m"
    exit
fi

if [[ "$1" =~ mmc ]]; then
    p="p"
fi


dd if=/dev/zero of=$1 bs=512 count=1

sfdisk --force -uM $1 << EOF
,16,0x53
,,83
EOF

if [ ! -b "${1}${p}1" ]; then
    echo -e "\033[1mError: partition ${1}${p}1 not found\033[0m"
    exit
fi

if [ ! -b "${1}${p}2" ]; then
    echo -e "\033[1mError: partition ${1}${p}2 not found\033[0m"
    exit
fi

if [ -n "$2" ]; then
    echo -e "\033[1mWriting image $2 to partition ${1}${p}1 ...\033[0m"
    dd if=/dev/zero of=${1}${p}1 bs=512 count=4
    dd if=$2 of=${1}${p}1 bs=512 seek=4 conv=sync,notrunc
else
    exit
fi

if [ -n "$3" ]; then
    echo -e "\033[1mMake $3 fs on ${1}${p}2 ...\033[0m"
    mkfs -t $3 ${1}${p}2
fi
